spring.application.name=aj

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_assembly
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.sheets.credentials-path=classpath:service-account.json
google.sheets.spreadsheet-id=1oNUr3C-GW8QFLm-V2tLKJRFOec1LtRoAw-cMcTBg-Cc
google.sheets.range=1479903952!A2:Q
google.sheets.default-assembly-id=1

mobizon.enabled=false
mobizon.api-key=kz26c92bf7f3347240c5b71a5389c6ff568b1c4526934a534f612eb60027f7f55da31f

server.port=8080

jwt.secret=smartAssemblySecretKey2026VeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000

spring.sql.init.mode=always
spring.datasource.password=assaemblylkk45@f

mobizon.enabled=true
mobizon.api-key=kz26c92bf7f3347240c5b71a5389c6ff568b1c4526934a534f612eb60027f7f55da31f