spring.application.name=aj

spring.datasource.url=jdbc:postgresql://localhost:5432/db_smart_assembly
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

google.sheets.credentials-path=classpath:smart-assembly-492708-3bd3f8ffb35b.json
google.sheets.spreadsheet-id=1RVUsKkoXUmpaJRUv0_boj-MDzN_ZEh7XtG49p-AJoHo

mobizon.enabled=false
mobizon.api-key=kz26c92bf7f3347240c5b71a5389c6ff568b1c4526934a534f612eb60027f7f55da31f

server.port=8080

jwt.secret=smartAssemblySecretKey2026VeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000